---
- name: installe packeges
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - httpd
    - mod_ssl
    - php

- name: start apache service
  service: 
    name: httpd
    state: started
    enabled: yes

- name: permit traffic in default zone for https service
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items:
    - http
    - https

- name: permit traffic in default zone for http service
  ansible.posix.firewalld:
    service: http
    permanent: yes
    state: enabled

- name: Copy index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: restart_apache