---
- name: Create partition on /dev/sdb
  parted:
    device: /dev/sdb
    number: 1
    part_end: 800MB
    flags: [ lvm ]
    state: present

- name: Create lvm group
  lvg:
    vg: vg_database
    pvs: /dev/sdb1

- name: Create logical volume
  lvol:
    vg: vg_database
    lv: lv_mysql
    size: 512

- name: Create XFS on the lvm
  filesystem:
    fstype: xfs
    dev: /dev/vg_database/lv_mysql

- name: Create a directory to mount the lvm
  file:
    path: /mnt/mysql_backups
    state: directory

- name: Mount the created filesystem permanently
  mount:
    path: /mnt/mysql_backups
    src: /dev/vg_database/lv_mysql
    fstype: xfs
    state: mounted

- name: Install mysql-community-server
  yum:
    name: mysql-community-server

- name: Permit traffic on port 3306 for MySQL
  firewalld:
    port: "3306/tcp"
    permanent: yes
    immediate: yes
    state: enabled

- name: make sure mysqld service is running
  service:
    name: mysqld
    state: started
    enabled: yes

- name: MySQL root user password
  mysql_user:
    name: root
    password: "{{ database_password }}"
    login_unix_socket: /var/lib/mysql/mysql.sock
    state: present

- name: Copy my.cnf global MySQL configuration.
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: 0644